version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=delphic_games
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  delphicgames:
    build:
      context: .
      dockerfile: DelphicGames/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5433;Database=delphic_games;Username=user;Password=123456
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
volumes:
  db-data: