version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  delphicgames:
    build:
      context: .
      dockerfile: DelphicGames/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - EmailSettings__From=${EmailSettings__From}
      - EmailSettings__SmtpServer=${EmailSettings__SmtpServer}
      - EmailSettings__Port=${EmailSettings__Port}
      - EmailSettings__Username=${EmailSettings__Username}
      - EmailSettings__Password=${EmailSettings__Password}
      - EmailSettings__EnableSendConfirmationEmail=${EmailSettings__EnableSendConfirmationEmail}
      - RootUser__Email=${RootUser__Email}
      - RootUser__Password=${RootUser__Password}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
volumes:
  db-data: